version: '3.4'

services:
  mypostgresdb:
    container_name: mypostgresdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=clothes
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/
      - ./path/to/certificate.pfx:/https/certificate.pfx

  clothes.api:
    container_name: clothes.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=mypostgresdb;Port=5432;Database=clothes;User Id=p>
    depends_on:
      - mypostgresdb
    ports:
      - "6001:80"
      - "6061:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

volumes:
  postgres_catalog:

