version: '3.4'

services:
  mypostgresdb:
      image: postgres

  clothes.api:
      image: ${DOCKER_REGISTRY-}clothesapi
      build:
          context: .
          dockerfile: clothes.api/Dockerfile

